sudo: required
services:
  - docker

before_install:
  - docker build -t MurLeeDas/docker-react-proj -f Dockerfile.dev .

script:
  - docker run MurLeeDas/docker-react-proj npm run test -- --coverage


